dotenv: .env
wallets:
  from_key: ${PRIVATE_KEY}
dependencies:
  - smartcontractkit/chainlink-brownie-contracts@0.3.1
networks:
  rinkeby:
    eth_usd_price_feed: "0x9326BFA02ADD2366b30bacB125260Af641031331"
    verify: True
  development:
    verify: False
  ganache-local:
    verify: False
compiler:
  solc:
    remappings:
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@0.3.1'